apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-router-config
  namespace: app-oficina-tech
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      proxy_connect_timeout     10s;
      proxy_send_timeout        60s;
      proxy_read_timeout        60s;

      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      upstream ms1 { server ms1-service:8080; }
      upstream ms2 { server ms2-service:8082; }
      upstream ms3 { server ms3-service:8083; }

      server {
        listen 30080;
        server_name _;

        add_header 'Access-Control-Allow-Origin'  '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With' always;

        location = /health {
          access_log off;
          return 200 '{"status":"ok","router":"nginx"}';
          add_header Content-Type application/json;
        }

        if ($request_method = 'OPTIONS') {
          return 204;
        }

        location ~ ^/(auth|users|customers|vehicles)(/|$) {
          proxy_pass http://ms1;
        }

        location ~ ^/(service-orders|payments)(/|$) {
          proxy_pass http://ms2;
        }

        location ~ ^/(services|products)(/|$) {
          proxy_pass http://ms3;
        }

        location / {
          return 404 '{"errors":[{"code":"NOT_FOUND","message":"Route not found"}]}';
          add_header Content-Type application/json;
        }
      }
    }
